### ISSUE TITLE
build info error 

### ISSUE THREAD

**Issue by hezhenfei8** [codeandrobots/codeandrobots-app#50]
problem1：
execute ：　npm install husky@next --save-dev

build info:
E:\Project\Petoi_cat\android\0329\codeandrobots-app-master>npm install husky@next --save-dev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for husky@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.LAPTOP-NG0R56A6\AppData\Roaming\npm-cache\_logs\2020-03-28T16_15_02_536Z-debug.log
---------------------------------------------------------------------------------------------------------

jump over problem1：
problem 2:
execute : react-native run-android --variant=devDebug

build info:
BUILD SUCCESSFUL in 24s
301 actionable tasks: 2 executed, 299 up-to-date
info Running d:\Android\Sdk/platform-tools/adb -s 436221bc reverse tcp:8081 tcp:8081
info Starting the app on 436221bc (d:\Android\Sdk/platform-tools/adb -s 436221bc shell am start -n com.codeandrobots/com.codeandrobots.MainActivity)...
Starting: Intent { cmp=com.codeandrobots/.MainActivity }
Error type 3
Error: Activity class {com.codeandrobots/com.codeandrobots.MainActivity} does not exist.

**Comment by chico** [comment]
@hezhenfei8 

For **problem 1**, please try `npm install husky --save-dev` although you can skip this step since husky is only used when making commits to the repository.

---

For **problem 2**, see https://github.com/codeandrobots/codeandrobots-app/blob/master/TROUBLESHOOTING.md#activity-class-comcodeandrobotscomcodeandrobotsmainactivity-does-not-exist:
 * If you see the error `Activity class {com.codeandrobots/com.codeandrobots.MainActivity} does not exist` then **all is OK but you have to find and launch the Code & Robots app manually from your device**. This error occurs because react-native CLI doesn't work well yet with Android variants.

**Comment by chico** [comment]
Closing as hopefully https://github.com/codeandrobots/codeandrobots-app/issues/50#issuecomment-605790088 addresses the issue raised.
